### ISSUE TITLE
はじめまして、少し質問があります。

### ISSUE THREAD

**Issue by dcash872** [ftngrn/income#8]
このアプリを自分のローカル環境に置いて試してみたのですが、ログイン画面がトップにくるので、DBにスタッフのデータが何もないとログインできないと思い、データを入れて見たのですが、エラーが返ってきます。スタッフの新規登録にも飛べないので、どうすればログインできるデータを入れることができるのか、お教え願えますか？

よろしくお願いいたします。

**Comment by ftngrn** [comment]
src/Controller/AppController.php
60行目のコメントを外し
61行目の先頭にコメントを入れることで
/staffs/add からスタッフの追加ができると思います。（URLは手打ちする必要があると思います）

`//$this->Auth->allow();`
`$this->Auth->allow(['login', 'logout']);`
　↓
`$this->Auth->allow();`
`//$this->Auth->allow(['login', 'logout']);`

**Comment by dcash872** [comment]
回答いただき、大変ありがとうございました。
こちらで、暗号化がSHA256, SHA512ということでパスワードを
ハッシュ化したものを改めてDBに入力したところ、認証が通り、ログインすることができました。

こちらの方法でも試したいと思います。

**Comment by ftngrn** [comment]
承知しました。では、closeとさせて頂きます。
